version: 2

linters:
  enable:
    - govet
    - ineffassign
    - misspell
    - unconvert
    - prealloc
    - nakedret
    - gocyclo
    - dupl
    - gosec

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100

issues:
  max-issues-per-linter: 100
  max-same-issues: 10
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - errcheck
    - path: examples/
      linters:
        - errcheck
        - gosec
    - text: "G101|G404|G304"  # Allow some security issues temporarily
      linters:
        - gosec